title: Ganesh Magal
author:
  name: Ganesh Magal
  email: ganesh@domain.com
description: Random things on everything electronics and software engineering
theme: minima
minima:
  skin: dark
  date_format: "%b %-d, %Y"
markdown: kramdown
show_excerpts: true
plugins:
 - jekyll-feed
 - jekyll-seo-tag
