title: Ganesh
author:
  name: Ganesh Magal
  email: ganesh@magal.com
description: > Random things on everything electronics and software engineering
theme: minima
markdown: kramdown
show_excerpts: true
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
